### PR TITLE
Added 0/1 Knapsack Problem

### LINKED ISSUE #2: 0/1 Knapsack problem
@tuhinsunny I would like to add this algorithm under SSoc 2.0. Please assign me this issue.

### PR DESCRIPTION
**Pull request by MAYURIKOTHARI299**
Close #2

### CODE REVIEW

**Comment by MAYURIKOTHARI299** [comment]
@tuhinsunny please accept under tag SSoC 2.0

**Comment by MAYURIKOTHARI299** [comment]
@tuhinsunny please add the tag for SSoC'23

**Comment by tuhinsunny** [comment]
How can I add the tag? Can u kindly tell.

**Comment by MAYURIKOTHARI299** [comment]
@tuhinsunny you will have to add correct  labels to my merged PRs as only maintainers can do it otherwise itwon't get count.Please do it as soon possible.

**Pull request merged**
